"""Add intermediate CA support

Revision ID: 0103fe2e44a0
Revises: 861981bf12f8
Create Date: 2026-02-03 13:38:31.968143

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0103fe2e44a0"
down_revision: Union[str, Sequence[str], None] = "861981bf12f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("certificate_authorities", schema=None) as batch_op:
        batch_op.add_column(sa.Column("parent_ca_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("path_length", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_ca_parent_ca_id", "certificate_authorities", ["parent_ca_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("certificate_authorities", schema=None) as batch_op:
        batch_op.drop_constraint("fk_ca_parent_ca_id", type_="foreignkey")
        batch_op.drop_column("path_length")
        batch_op.drop_column("parent_ca_id")

    # ### end Alembic commands ###
