"""Add allow_leaf_certs to CA

Revision ID: 0284d86b8ece
Revises: 0103fe2e44a0
Create Date: 2026-02-03 14:53:29.678239

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0284d86b8ece"
down_revision: Union[str, Sequence[str], None] = "0103fe2e44a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("certificate_authorities", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "allow_leaf_certs",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("1"),
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("certificate_authorities", schema=None) as batch_op:
        batch_op.drop_column("allow_leaf_certs")

    # ### end Alembic commands ###
