"""add crl_base_url to certificate_authorities

Revision ID: 109b7b44c8ee
Revises: b9a1e91948b5
Create Date: 2026-04-13 16:06:17.024629

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "109b7b44c8ee"
down_revision: Union[str, Sequence[str], None] = "b9a1e91948b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("certificate_authorities", schema=None) as batch_op:
        batch_op.add_column(sa.Column("crl_base_url", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("certificate_authorities", schema=None) as batch_op:
        batch_op.drop_column("crl_base_url")

    # ### end Alembic commands ###
