"""Initial migration

Revision ID: 9d90136388ec
Revises:
Create Date: 2026-01-30 11:46:15.704367

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d90136388ec"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "certificate_authorities",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("subject_dn", sa.String(), nullable=False),
        sa.Column("key_size", sa.Integer(), nullable=False),
        sa.Column("valid_days", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("private_key", sa.String(), nullable=False),
        sa.Column("certificate", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("certificate_authorities", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_certificate_authorities_name"),
            ["name"],
            unique=False,
        )

    op.create_table(
        "organizations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_organizations_name"),
            ["name"],
            unique=True,
        )

    op.create_table(
        "certificates",
        sa.Column("common_name", sa.String(), nullable=False),
        sa.Column("subject_dn", sa.String(), nullable=False),
        sa.Column(
            "certificate_type",
            sa.Enum("CA", "SERVER", "CLIENT", name="certificatetype"),
            nullable=False,
        ),
        sa.Column("key_size", sa.Integer(), nullable=False),
        sa.Column("valid_days", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("VALID", "REVOKED", "EXPIRED", name="certificatestatus"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("private_key", sa.String(), nullable=True),
        sa.Column("certificate", sa.String(), nullable=False),
        sa.Column("serial_number", sa.String(), nullable=False),
        sa.Column("not_before", sa.DateTime(), nullable=False),
        sa.Column("not_after", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("issuer_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["issuer_id"],
            ["certificate_authorities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("certificates", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_certificates_common_name"),
            ["common_name"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_certificates_serial_number"),
            ["serial_number"],
            unique=False,
        )

    op.create_table(
        "crl_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("serial_number", sa.String(), nullable=False),
        sa.Column("revocation_date", sa.DateTime(), nullable=False),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("ca_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ca_id"],
            ["certificate_authorities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("crl_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_crl_entries_serial_number"),
            ["serial_number"],
            unique=False,
        )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("SUPERUSER", "ADMIN", "USER", name="userrole"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_users_email"),
            ["email"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("ix_users_username"),
            ["username"],
            unique=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("crl_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_crl_entries_serial_number"))

    op.drop_table("crl_entries")
    with op.batch_alter_table("certificates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_certificates_serial_number"))
        batch_op.drop_index(batch_op.f("ix_certificates_common_name"))

    op.drop_table("certificates")
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organizations_name"))

    op.drop_table("organizations")
    with op.batch_alter_table("certificate_authorities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_certificate_authorities_name"))

    op.drop_table("certificate_authorities")
    # ### end Alembic commands ###
