services:
  api:
    volumes:
      - ../data:/app/data
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/fastpki
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    
  # In production, include the PostgreSQL service by default
  db:
    profiles: []